export const GET_DIETS = 'GET_DIETS';

export const FILTER_BY_DIETS = 'FILTER_BY_DIETS';
export const CLEAN_FILTER_BY_DIETS = 'CLEAN_FILTER_BY_DIETS';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPES_ORDERED = 'GET_RECIPES_ORDERED';


export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

